apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/waltermk/agentops-wmk.git
    targetRevision: main
    path: apps/hermes-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true